name: trial-prometheus

networks:
  grafana:

volumes:
  grafana_data:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - grafana
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - grafana
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - grafana
