# https://docs.docker.com/compose/compose-file/
version: "3.9"

networks:
  grafana:

volumes:
  grafana_data:

services:
  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - grafana
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - grafana
